---
- name: "Install Zabbix Agent on Ubuntu"
  hosts: all
  become: true

  tasks:
    - name: "1/7 Update apt cache"
      apt:
        update_cache: yes

    - name: "2/7 Install prerequisites (wget)"
      apt:
        name: wget
        state: present

    - name: "3/7 Download Zabbix release package (force)"
      shell: |
        wget -O /home/kirill/zabbix-release.deb https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_6.0+ubuntu22.04_all.deb

    - name: "4/7 Verify that file exists"
      stat:
        path: /home/kirill/zabbix-release.deb
      register: deb_file

    - name: "5/7 Install Zabbix release package"
      apt:
        deb: "/home/kirill/zabbix-release.deb"
      when: deb_file.stat.exists

    - name: "6/7 Update apt after adding repo"
      apt:
        update_cache: yes

    - name: "7/7 Install Zabbix agent"
      apt:
        name: zabbix-agent
        state: latest

    - name: "8/7 Configure Zabbix agent (set Server IP)"
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server=127.0.0.1'
        replace: 'Server=192.168.30.4'
      notify: restart zabbix-agent

  handlers:
    - name: restart zabbix-agent
      systemd:
        name: zabbix-agent
        state: restarted
        enabled: yes
